version: "3.8"

services:
  mysql-db:
    container_name: football_mysql
    image: mysql:8.0
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306"
    env_file:
      - env_db_compose.txt

  football-manager:
    build: .
    container_name: football_manager_app
    restart: always
    depends_on:
      - mysql-db
    ports:
      - "8080:8080"
    env_file:
      - env_compose.txt

volumes:
  db_data:
